# Generated by Django 2.1.4 on 2019-01-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_remove_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='sample', max_length=1000),
            preserve_default=False,
        ),
    ]
